class CFG:
    debug=False
    apex=False
    print_freq=100
    num_workers=4
    model_name='swinv2_base_window12to24_192to384_22kft1k'
    size=384
    scheduler='CosineAnnealingWarmRestarts' # ['ReduceLROnPlateau', 'CosineAnnealingLR', 'CosineAnnealingWarmRestarts']
    epochs=10
    #factor=0.2 # ReduceLROnPlateau
    #patience=4 # ReduceLROnPlateau
    #eps=1e-6 # ReduceLROnPlateau
    #T_max=10 # CosineAnnealingLR
    T_0=10 # CosineAnnealingWarmRestarts
    lr=1e-4
    min_lr=1e-6
    batch_size=8
    weight_decay=1e-6
    gradient_accumulation_steps=1
    max_grad_norm=1000
    seed=42
    target_size=102
    target_col='class'
    n_fold=1
    trn_fold=[0]
    train=True
    inference=False
    device = "cuda:0"